number_of_robots: 5
# command_topics: 
#   - "/spacenav/twist/repub"
#   - "/spacenav/twist/repub2"
#   - "/spacenav/twist/repub3"
closed_loop_swarm_command_topic: "/desired_swarm_vel"

open_loop_swarm_command_topic: "/just_swarm_vel"

closed_loop_command_topics:
  - "/oarbot_silver/cmd_vel"
  - "/oarbot_blue/cmd_vel"
  - "/ridgeback/cmd_vel"
  - "/husky_black/cmd_vel"
  - "/husky_blue/cmd_vel"

open_loop_command_topics:
  - "/just_robot_vel_0"
  - "/just_robot_vel_1"
  - "/just_robot_vel_2"
  - "/just_robot_vel_3"
  - "/just_robot_vel_4"
  
robot_node_names:
  - ["/uwb_front_oarbot_silver","/uwb_back_oarbot_silver","/sensor_fusion_oarbot_silver","/oarbot_silver_ctrl"]
  - ["/uwb_front_oarbot_blue","/uwb_back_oarbot_blue","/sensor_fusion_oarbot_blue","/oarbot_blue_ctrl"]
  - []
  - []
  - []
robot_type_information:
  - "OB_S"
  - "OB_B"
  - "RB"
  - "H_BLK"
  - "H_BLU"


input_command_topic: 'deadman_switch_spacenav_twist'

sync_frames_topic:  'move_desired_to_current'
