feedback_gain_xy: 3.0
# feedback_gain_theta: 1.0
is_offset_mode: True

cmd_input_type: 'State2D'
#cmd_input_type: 'Twist'
cmd_input_topic_name: 'desired_state'
position_feedback_topic_name: 'position'
control_cmd_publish_topic_name: 'cmd_vel'
frame_name: 'husky_blue_tt_d' # desired

vel_lim_x: 1.0
vel_lim_y: 1.0
vel_lim_theta: 2.0

space_mouse_topic_name: '/tablet/spacenav/joy'

p_x: 0.3713 # m
p_y: 0.0 # m
turntable_position_topic_name: 'turntable_position'
tf_turntable_frame_name: 'husky_blue_tt'
tf_robot_frame_name: 'husky_blue_fusion'
