velocity_feedback_type: "Twist"
velocity_feedback_topic_name: "vel_feedback"
uwb_front_topic_name: "uwb_serial_front"
uwb_back_topic_name: "uwb_serial_back"

uwb_front_id: '48D3'
uwb_back_id: '43A9'

tf_frame_name_uwb: "husky_black_uwb"
tf_frame_name_fused: "husky_black_fusion"
position_feedback_topic_name: "position"

tag_loc_front_x: 0.288
tag_loc_front_y: 0.255

tag_loc_back_x: -0.268
tag_loc_back_y: -0.255

tag_z_height: 0.5

uwb_meas_std: [0.5, 0.5, 0.2] # comes from uwb sensor readings data  # TODO
odom_meas_std: [0.0001, 0.0001, 0.00005] # comes from encoder readings experiments # TODO
process_pos_std: [0.3, 0.3, 0.4] # these are half of the max accelerations of the desired state # TODO
process_vel_std: [0.3, 0.3, 0.4] # these are half of the max accelerations of the desired state # TODO

