velocity_feedback_topic_name: "vel_feedback"
motor_command_topic_name: "motor_command"
motor_feedback_topic_name: "motor_feedback"
republished_spacemouse: "e_stop_cmd_vel"
serial_front: "/dev/serial/by-path/pci-0000:00:14.0-usb-0:4.1:1.0"
serial_back: "/dev/serial/by-path/pci-0000:00:14.0-usb-0:4.2:1.0"

radius_wheel: 0.1016 # wheel radius
l_x: 0.21463 # meter
l_y: 0.22008 # meter
total_gear_ratio: 9.72 # 1/((Chain Driver Ratio)*(gear_ratio)) = 1/((10.0/15.0)*(1.0/81.0*200/16))
