velocity_feedback_type: "Twist"
velocity_feedback_topic_name: "vel_feedback"
uwb_front_topic_name: "uwb_serial_front"
uwb_back_topic_name: "uwb_serial_back"

uwb_front_id: '43AA'
uwb_back_id: '1563'

tf_frame_name_uwb: "oarbot_blue_uwb"
tf_frame_name_fused: "oarbot_blue_fusion"
position_feedback_topic_name: "position"

tag_loc_front_x:  0.326176 #0.3060
tag_loc_front_y: -0.198747 #-0.1976

tag_loc_back_x: -0.060612 # 0.0391
tag_loc_back_y:  0.188040 # 0.2110

# tag_z_height: 0.75

uwb_meas_std: [0.5, 0.5, 0.2] # comes from uwb sensor readings data 
odom_meas_std: [0.0001, 0.0001, 0.00005] # comes from encoder readings experiments
process_pos_std: [0.3, 0.3, 0.4] # these are half of the max accelerations of the desired state
process_vel_std: [0.3, 0.3, 0.4] # these are half of the max accelerations of the desired state

