velocity_feedback_topic_name: "vel_feedback"
motor_command_topic_name: "motor_command"
motor_feedback_topic_name: "motor_feedback"
republished_spacemouse: "cmd_vel"
serial_front: "/dev/serial/by-path/pci-0000:00:14.0-usb-0:4.1:1.0"
serial_back: "/dev/serial/by-path/pci-0000:00:14.0-usb-0:4.2:1.0"