velocity_feedback_topic_name: "oarbot_silver/vel_feedback"
motor_command_topic_name: "oarbot_silver/motor_command"
republished_spacemouse: "spacenav/twist/repub2"
serial_front: "/dev/serial/by-path/pci-0000:00:14.0-usb-0:4.3:1.0"
serial_back: "/dev/serial/by-path/pci-0000:00:14.0-usb-0:4.6:1.0"
