velocity_feedback_type: "Twist" # "Odometry"
velocity_feedback_topic_name: "vel_feedback" # "ridgeback_velocity_controller/odom"
uwb_front_topic_name: "uwb_serial_front"
uwb_back_topic_name: "uwb_serial_back"

uwb_front_id: '0CAD'
uwb_back_id: '0D8F'

tf_frame_name_uwb: "ridgeback_uwb"
tf_frame_name_fused: "ridgeback_fusion"
position_feedback_topic_name: "position"

# RIDGEBACK
#TAG_LOC_FRONT = np.array([[0.5054],[0.0254]])
#TAG_LOC_BACK = np.array([[-0.17405],[0.0254]])

tag_loc_front_x: 0.5054
tag_loc_front_y: 0.0254

tag_loc_back_x: -0.17405
tag_loc_back_y: 0.0254

uwb_meas_std: [0.5, 0.5, 0.2] # comes from uwb sensor readings data 
odom_meas_std: [0.0001, 0.0001, 0.00005] # comes from encoder readings experiments
process_pos_std: [0.3, 0.3, 0.4] # these are half of the max accelerations of the desired state
process_vel_std: [0.3, 0.3, 0.4] # these are half of the max accelerations of the desired state